
export const STUDENTS_LIST_REQUEST = "STUDENTS_LIST_REQUEST";
export const STUDENTS_LIST_SUCCESS = "STUDENTS_LIST_SUCCESS";
export const STUDENTS_LIST_FAIL = "STUDENTS_LIST_FAIL";

export const STUDENTS_CREATE_REQUEST = "STUDENTS_CREATE_REQUEST";
export const STUDENTS_CREATE_SUCCESS = "STUDENTS_CREATE_SUCCESS";
export const STUDENTS_CREATE_FAIL = "STUDENTS_CREATE_FAIL";

export const STUDENTS_UPDATE_REQUEST = "STUDENTS_UPDATE_REQUEST";
export const STUDENTS_UPDATE_SUCCESS = "STUDENTS_UPDATE_SUCCESS";
export const NOTES_UPDATE_FAIL = "NOTES_UPDATE_FAIL";

export const STUDENTS_DELETE_REQUEST = "STUDENTS_DELETE_REQUEST";
export const STUDENTS_DELETE_SUCCESS = "STUDENTS_DELETE_SUCCESS";
export const STUDENTS_DELETE_FAIL = "STUDENTS_DELETE_FAIL";